/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JPassignment;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Staff_Edit extends javax.swing.JFrame {

    /**
     * Creates new form Staff_Edit
     */
    public Staff_Edit() {
        initComponents();
        namefield.setText(Staff_View.r.getname());
        icnofield.setText(Staff_View.r.geticno());
        contnofield.setText(Staff_View.r.getcontno());
        emailfield.setText(Staff_View.r.getemail());
        String size;
        switch (Staff_View.r.getposition()) {
             case "Staff" -> positioncombox.setSelectedIndex(0);
             case "Manager" -> positioncombox.setSelectedIndex(1);
             default -> positioncombox.setSelectedIndex(1);
         }
        passwordfield.setText(Staff_View.r.getpassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        icnofield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        emailfield = new javax.swing.JTextField();
        contnofield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        positioncombox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Contact Number: ");

        jLabel7.setText("Position: ");

        jLabel5.setText("Email: ");

        icnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icnofieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Password: ");

        contnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contnofieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Edit Staff Detail");

        jLabel1.setText("Name: ");

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Identity Card Number: ");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        positioncombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager" }));
        positioncombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positioncomboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(107, 107, 107)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icnofield)
                    .addComponent(contnofield)
                    .addComponent(emailfield)
                    .addComponent(namefield)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updatebtn))
                    .addComponent(passwordfield)
                    .addComponent(positioncombox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(icnofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contnofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(positioncombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(updatebtn))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contnofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contnofieldActionPerformed

    private void icnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icnofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icnofieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Staff_View m = new Staff_View();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Staff_View m = new Staff_View();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        
        boolean flag = true;
        
        String regex = "[0-9]+";
        String regex2 = "^[a-zA-Z ]*$";
        String regex3 = "^[0-9A-Z]+$";
        String regex4 = "^[0-9a-zA-Z]+$";
        Pattern passchk = Pattern.compile(regex4);
        Pattern p = Pattern.compile(regex);
        Pattern namechk = Pattern.compile(regex2);
        Pattern passnochk = Pattern.compile(regex3);
        Matcher m = p.matcher(this.contnofield.getText());
        Matcher i = p.matcher(this.icnofield.getText());
        Matcher b = namechk.matcher(this.namefield.getText());
        Matcher s = passchk.matcher(this.passwordfield.getText());

        
         if (this.namefield.getText().isEmpty() && this.icnofield.getText().isEmpty() && this.contnofield.getText().isEmpty()&& this.emailfield.getText().isEmpty() && this.passwordfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all text fields.");
            flag = false;
        } else {
            if (m.matches() == false || this.contnofield.getText().length() < 10) {
                JOptionPane.showMessageDialog(null, "Please ensure the contact number consists only numbers and equal or more than 10 digits");
                flag = false;
            }
         
             if (i.matches()== false || this.icnofield.getText().length() != 12){
                JOptionPane.showMessageDialog(null, "Please ensure the IC number are only numbers and only 12 digits");
                flag = false;
            }
              
              if (b.matches()== false){
                JOptionPane.showMessageDialog(null, "Name entered should only consist of alphabets");
                flag = false;
            }

            if (!emailfield.getText().contains("@") || emailfield.getText().contains(" ") || !emailfield.getText().contains(".com")) {
                JOptionPane.showMessageDialog(null, "Please ensure correct format of email");
                flag = false;
            }
            if (s.matches()== false){
                JOptionPane.showMessageDialog(null, "Password entered should only consist of alphabets and numbers");
                flag = false;
            }
            
         }
       
         if (flag == true) {
        String name =namefield.getText();
        String icno = icnofield.getText();
        String contno = contnofield.getText();
        String email = emailfield.getText();
        String position;
            switch (positioncombox.getSelectedIndex()) {
                case 0 ->                 {
                        position ="Staff";
                    }
                case 1 ->                 {
                       position ="Manager";
                    }
                default -> {
                      position ="Staff";
                }
        }        
        String password = passwordfield.getText();
     
        Staff staff = new Staff();
        staff.setstaffID(Staff_View.r.getstaffID());  
        staff.seticno(icno);
        staff.setcontno(contno);
        staff.setname(name);
        staff.setemail(email);
        staff.setposition(position);
        staff.setpassword(password);

       if (staff.update()){
            JOptionPane.showMessageDialog(this, "Staff detail is updated");          
        Staff_View o = new Staff_View();
        this.hide();
        o.setVisible(true);
       } 
      }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void positioncomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positioncomboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positioncomboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contnofield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField icnofield;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JComboBox<String> positioncombox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
